name: Jest Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Use the latest version of checkout action

      - name: Setup R environment
        uses:  r-lib/actions/setup-r@v2 # Use the latest version of setup-r

      - name: Install dpendencies
        run: Rscript -e 'install.packages("remotes")' and Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Install covr dependencies
        run: Rscript -e 'install.packages("covr")'

      - name: Generate coverage report
        run: Rscript -e 'covr::package_coverage(type = "all", quiet = FALSE, clean = TRUE, report_type = "html", file = "coverage.xml")'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
